### ISSUE TITLE
my first bug!

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_next_generation#1]
```
ocs@last11e:~/python/LAST_next_generation/bin$ ./last-unit-server start

....

2024-01-07 13:12:02,247 - INFO     - {last-unit-server:<module>:326515:MainThread:140470407927616} -  FastApi routers maker succeeded!
Traceback (most recent call last):
  File "unit/unit-server.py", line 34, in <module>
    import unit
  File "/home/ocs/python/LAST_next_generation/unit/unit.py", line 7, in <module>
    import lipp
  File "/home/ocs/python/LAST_next_generation/unit/lipp.py", line 3, in <module>
    from utils import Equipment, equipment_ids, init_log, datetime_decoder, DateTimeEncoder, TriState, LockWithTimeout
ImportError: cannot import name 'LockWithTimeout' from 'utils' (/home/ocs/python/LAST_next_generation/unit/utils.py)
```

**Comment by EastEriq** [comment]
On last11w too.

**Comment by blumzi** [comment]
Fixed.  LockWithTimeout was not used
