### ISSUE TITLE
`unit` misses a `stop` method, I think

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_next_generation#2]
```
2024-01-21 14:01:07,071 - INFO     - {last-unit-server:shutdown:2023213:MainThread:139927350937408} -  shutdown by shutdown query
2024-01-21 14:01:07,072 - INFO     - {unit-FastApi:quit:2023213:MainThread:139927350937408} -  Quiting
INFO:     127.0.0.1:57190 - "GET /shutdown HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "unit/unit-server.py", line 66, in shutdown
    await unit.unit.quit()
  File "/home/ocs/python/LAST_next_generation/unit/unit.py", line 171, in quit
    self.timer.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
INFO:     Shutting down
ocs@last11e:~$ INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2023213]
```

**Comment by blumzi** [comment]
It is not the unit that doesn't have a 'stop'.  As the error clearly states, self.timer has at this point-in-time 'None' and thus, being of 'NoneType' it doesn't have a 'stop' attribute.

I have fixed this sequence
