### ISSUE TITLE
device forwarding doesn't work anymore (was working thursday)

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_next_generation#21]
Lipp servers started correctly on last11e and 11w. Logger on 11w periodically succeeds in probing focuser 3 and 4 as well as camera 3 and 4.
However
```
>> Unit.Focuser(3).Pos
17:03:07.880 [INF] [pid=1363183] Remote.send: sending URL='http://127.0.0.1:8000/last/api/v1/focuser/3/Pos'
17:03:08.001 [ERR] [pid=1363183] Error: 'HTTP/1.1 500 Internal Server Error' (Url='http://127.0.0.1:8000/last/api/v1/focuser/3/Pos')
```
Ditto with 4 and cameras 3 and 4. 1 and 2 work regularly when queried on 11e.

Conversely (tried in the uvicorn webby for a change), 11w can query its devices, but not focusers, cameras 1 & 2  nor mount.

**Comment by EastEriq** [comment]
More on this in the stdout lipp log, e.g. querying focuser 3 from 11e:
```
INFO:     127.0.0.1:60712 - "GET /last/api/v1/focuser/3/Connected HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 292, in app
    content = await serialize_response(
  File "/home/ocs/python/LAST_next_generation/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'bool_type', 'loc': ('response',), 'msg': 'Input should be a valid boolean', 'input': {'RequestId': 10, 'Value': True}, 'url': 'https://errors.pydantic.dev/2.5/v/bool_type'}
```
Same traces (except for the counter of `RequestId`) when querying other other side devices, from either machine.
